2. Copy and Paste the Following GitHub Action Code for Linting
NOTE: Never, never, never add this file in or touch it in Repl.it. ONLY add it in from GitHub.
(If you do touch it in Repl.it, it will most likely lock your Repl and you will have to start all over again!)

##################################################
# Run Mr Coxall's Super Linter against code base #
##################################################
---
name: Mr Coxall's Super Linter
on: [push, pull_request]
jobs:
 run-linters:
   name: Mr Coxall's Super Linter
   runs-on: ubuntu-latest

   steps:
     - name: Check out Git repository
       uses: actions/checkout@main

     - name: Run GitHub Super Linter
       uses: github/super-linter@main
       env:
         VALIDATE_ALL_CODEBASE: true
         LINTER_RULES_PATH: /
         VALIDATE_CLANG_FORMAT: false
         VALIDATE_JAVASCRIPT_STANDARD: false
         VALIDATE_PYTHON_FLAKE8: false
         VALIDATE_GITLEAKS: false # for secrets detection
         VALIDATE_JSCPD: false # for copy and paste detection
         DEFAULT_BRANCH: main
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
